<?php

# Administrator settings
$conf['adminuser'] = "admin";
$conf['adminpass'] = "pass123";

# Default pathname to the TSIG key generated by dnssec-keygen(8).
$conf['nskey'] = "keys/Kddns.tld.+157+41090.key";

# Default nameserver to which the update will be sent.
$conf['nameserver'] = "localhost";

# Default TTL value (seconds) to use for the host record.
$conf['ttl'] = 60; # default 3600 seconds

# Path to tempfile for command script
$conf['tempdir'] = "/var/www/virtual/myserver.tld/htdocs/ddns/tmp/";

# Available languages, if you create translations, just add them here
$conf['lang'] = array("en","de");

# Default domain, if user don not specify, we will check if he is on this one
$conf['domain'] = 'ddns.tld';

# Verbose mode, write log to database
$conf['verbose'] = true;

# Default site, available options: register, update
$conf['site'] = 'update';

?>
