<?php

# Administrator settings
$conf['adminuser'] = "admin";
$conf['adminpass'] = "mysecretpass";

# Default pathname to the TSIG key generated by dnssec-keygen(8). See doc/howto-lang.html
$conf['nskey'] = "keys/xxxxxxxxxxxxx.key";

# Default nameserver to which the update will be sent.
$conf['nameserver'] = "localhost";

# Default TTL value (seconds) to use for the host record.
$conf['ttl'] = 60; # default 3600 seconds

# Path to tempfile for command script
$conf['tempdir'] = "/var/www/ddns/tmp";

# Available languages, if you create translations, just add them here
$conf['lang'] = array("en","de");

# Default domain, if user don not specify, we will check if he is on this one
$conf['domain'] = 'not-dyndns.com';

# Verbose mode, write log to database
$conf['verbose'] = true;

# Default site, available options: register, update
$conf['site'] = 'update';

?>